# Generated by Django 4.2.2 on 2023-08-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_service_options_alter_service_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='user',
            new_name='user_id',
        ),
    ]
